apiVersion: v1
kind: Pod
metadata:
  name: challenge4
  labels:
    name: myapp
spec:
  containers:
  - name: myapp
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    volumeMounts:
    - mountPath: /flag
      name: data-volume

  volumes:
  - name: data-volume
    hostPath:
      path: /flag
      type: Directory