apiVersion: v1
kind: Pod
metadata:
  name: challenge-5
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - mountPath: /flag
      name: flag
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
  volumes:
  - name: flag
    hostPath:
      path: /flag     
      type: Directory
  imagePullSecrets:
  - name: image-registry
  tolerations:
  - key: "node-role.kubernetes.io/master"
    operator: "Exists"
    effect: "NoSchedule"