apiVersion: v1
kind: Pod
metadata:
  name: base
  labels:
    name: base
spec:
  containers:
  - name: base
    image: temp2.azurecr.io/base:latest
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
  imagePullSecrets:
  - name: image-registry


---

apiVersion: v1
kind: Service
metadata:
  name: base_service
spec:
  type: NodePort
  selector:
    app: base
  ports:  
    - port: 22
      targetPort: 22
      nodePort: 30008