apiVersion: v1
kind: Pod
metadata:
  name: myapp
  labels:
    name: myapp
spec:
  containers:
  - name: nginx
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    envFrom:
      - configMapRef:
          name: app-configmaps


# kubectl create configmap app-configmaps --from-literal=app=color=blue
#kubectl create configmap app-configmaps --from-file=app_config.properties

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: app-configmaps
data:
  APP_COLOR: "blue"
  APP_MODE: "prod"



