apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: ds
spec:
  selector:
    matchLabels:
      app: app1
  template:
    metadata:
      labels:
        app: app
    spec:
     containers:
       - name: nginx
         image: nginx
         resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
     
