#k create secret generic <secret-name> --from-literal=<key>=<value>

apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque
data:
  user: YWRtaW4K
  password: YWRtaW4K

---

apiVersion: v1
kind: Pod
metadata:
  name: myapp
  labels:
    name: myapp
spec:
  containers:
  - name: nginx
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    envFrom:
      - secretRef:
          name: mysecret

---

apiVersion: v1
kind: Pod
metadata:
  name: myapp
  labels:
    name: myapp
spec:
  containers:
  - name: nginx
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    volumeMounts:
      - name: mysecret
        mountPath: "/temp/secret"
        readOnly: true
  volumes:
    - name: mysecret
      secret:
        secretName: mysecret


---


apiVersion: v1
kind: Pod
metadata:
  name: base
  labels:
    name: base
spec:
  containers:
  - name: base
    image: temp2.azurecr.io/challenge3
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
  imagePullSecrets:
  - name: image-registry

