apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9376
  selector:
    app: myapptype
    type: back-end


---

apiVersion: v1
kind: Endpoints
metadata:
  name: my-service
subsets:
  - addresses:
      - ip: 192.0.2.42
    ports:
      - port: 9376

---

apiVersion: v1
kind: Service
metadata:
  name: myapp-service
spec:
  type: NodePort
  selector:
    app: myapp
    type: front-end
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30008
  
---

#clusterIP, only works with supported cloud platforms

apiVersion: v1
kind: Service
metadata:
  name: myapp
spec:
  type: LoadBalancer
  selector:
    app: myapp
    type: front-end
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30008

